### ISSUE TITLE
Email API controller is broken

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/voting-tool-cms#44]
When user tries to access the /api/email endpoint there is an error

**Comment by jy-ham** [comment]
The email endpoint has no issues with any of the code.

In order for the controller to send off an email, it requires sending a POST request with a body that has
{
  EmailAddress: email,
  Subject: subject,
  Message: message
}

The problem was that in order to use the gmail smtp service, the account that is sending off the email had to have allowed insecure app access which it did not have. I have logged into the email account and allowed the feature, and have tested that an email is sent by sending a POST request through postman.
